#!/bin/bash

#Należy dodać plik z zad 1. do plików startowych shella tak aby przy logowaniu był on uruchamiany (utwórz odpowiendie dowiązanie symboliczne tak żeby wszystkie pliki z którymi pracujesz znajdowały się w katalogu project)

sudo ln -s /home/project/L1Z1 /etc/profile.d/powitanie.sh
